export const API_SUCCESS_MESSAGE                        = 'Successful'
export const TASK_CREATE_SUCCESS_MESSAGE                = 'Task was created successfully'
export const TASK_DELETE_SUCCESS_MESSAGE                = 'Task was deleted successfully'
export const TASK_UPDATE_SUCCESS_MESSAGE                = 'Task was updated successfully'
export const TASK_UNASSIGN_SUCCESS_MESSAGE              = 'Task was unassigned successfully'
export const TINYMCE_MEDIA_UPLOAD_URL                   = `${import.meta.env.VITE_API_URL}kinban-app/upload`
export const FIRST_DEV_STAGE_NAME                       = "To Do"
export const CREATE_PROJECT_SUCCESS_MESSAGE             = 'Project created successfully'
export const UNAUTHORIZED_CODE                          = 401
export const REGISTRATION_SUCCESS_MESSAGE               = "Registration successful! An email verification link has been sent";
export const APP_NAME                                   = `${import.meta.env.VITE_APP_NAME}`
export const EMAIL_VERIFICATION_SUCCESS_MESSAGE         = "Verification successful! Please sign in";
export const EMAIL_VERIFICATION_RESEND_SUCCESS_MESSAGE  = "Verification link was resent successfully!";
